# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_KCALS', models.IntegerField()),
                ('total_protein', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_fat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_meal', models.CharField(max_length=250)),
                ('KCALS', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('daily_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.DailyDiet')),
            ],
        ),
    ]
