# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20170507_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
