# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_meal_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydiettotals',
            name='date',
            field=models.CharField(max_length=250),
        ),
    ]
