# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20170510_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydiettotals',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
