# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20170510_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydiettotals',
            name='date',
            field=models.DateField(),
        ),
    ]
